env:
  TERM: alacritty
window:
  padding:
    x: 0
    y: 0
  dynamic_padding: true
  startup_mode: Windowed
scrolling:
  history: 10000
  multiplier: 3
font:
  normal:
    family: monospace
    style: Regular
  bold:
    family: monospace
  italic:
    family: monospace
  size: 11
  offset:
    x: 1
    y: 4
  glyph_offset:
    x: 0
    y: 0
draw_bold_text_with_bright_colors: true
hide_cursor_when_typing: true
live_config_reload: true
colors:
  # Default colors
  primary:
    background: '0x2e3440'
    foreground: '0xb9bfca'
  # Normal colors
  normal:
    black:   '0x3b4252'
    red:     '0xbf616a'
    green:   '0xa3be8c'
    yellow:  '0xebcb8b'
    blue:    '0x81a1c1'
    magenta: '0xb48ead'
    cyan:    '0x88c0d0'
    white:   '0xe5e9f0'
  # Bright colors
  bright:
    black:   '0x465780'
    red:     '0xd06f79'
    green:   '0xb1d196'
    yellow:  '0xf0d399'
    blue:    '0x8cafd2'
    magenta: '0xc895bf'
    cyan:    '0x93ccdc'
    white:   '0xe7ecf4'
  indexed_colors:
    - { index: 16, color: '0xc9826b' }
    - { index: 17, color: '0xbf88bc' }
